name: Weekly QA Release Notes

on:
  schedule:
    # Runs every Wednesday at 3:30 AM UTC = 9:00 AM IST
    - cron: "30 3 * * 3"

jobs:
  post-weekly-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Weekly Notes Script
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
          python weekly_notes.py
